//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public class EffekseerBackendCore : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EffekseerBackendCore(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EffekseerBackendCore obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~EffekseerBackendCore() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EffekseerCorePINVOKE.delete_EffekseerBackendCore(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public EffekseerBackendCore() : this(EffekseerCorePINVOKE.new_EffekseerBackendCore(), true) {
  }

  public static EffekseerCoreDeviceType GetDevice() {
    EffekseerCoreDeviceType ret = (EffekseerCoreDeviceType)EffekseerCorePINVOKE.EffekseerBackendCore_GetDevice();
    return ret;
  }

  public static bool InitializeAsOpenGL() {
    bool ret = EffekseerCorePINVOKE.EffekseerBackendCore_InitializeAsOpenGL();
    return ret;
  }

  public static void Terminate() {
    EffekseerCorePINVOKE.EffekseerBackendCore_Terminate();
  }

}

}
