//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Effekseer.swig {

public class EffekseerEffectCore : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EffekseerEffectCore(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EffekseerEffectCore obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~EffekseerEffectCore() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EffekseerCorePINVOKE.delete_EffekseerEffectCore(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public EffekseerEffectCore() : this(EffekseerCorePINVOKE.new_EffekseerEffectCore(), true) {
  }

  public bool Load(byte[] data, int len, float magnification) {
    bool ret = EffekseerCorePINVOKE.EffekseerEffectCore_Load(swigCPtr, data, len, magnification);
    return ret;
  }

  public string GetTexturePath(int index, EffekseerTextureType type) {
    string ret = System.Runtime.InteropServices.Marshal.PtrToStringUni(EffekseerCorePINVOKE.EffekseerEffectCore_GetTexturePath(swigCPtr, index, (int)type));
    return ret;
  }

  public int GetTextureCount(EffekseerTextureType type) {
    int ret = EffekseerCorePINVOKE.EffekseerEffectCore_GetTextureCount(swigCPtr, (int)type);
    return ret;
  }

  public bool LoadTexture(byte[] data, int len, int index, EffekseerTextureType type) {
    bool ret = EffekseerCorePINVOKE.EffekseerEffectCore_LoadTexture(swigCPtr, data, len, index, (int)type);
    return ret;
  }

  public bool HasTextureLoaded(int index, EffekseerTextureType type) {
    bool ret = EffekseerCorePINVOKE.EffekseerEffectCore_HasTextureLoaded(swigCPtr, index, (int)type);
    return ret;
  }

  public string GetModelPath(int index) {
    string ret = System.Runtime.InteropServices.Marshal.PtrToStringUni(EffekseerCorePINVOKE.EffekseerEffectCore_GetModelPath(swigCPtr, index));
    return ret;
  }

  public int GetModelCount() {
    int ret = EffekseerCorePINVOKE.EffekseerEffectCore_GetModelCount(swigCPtr);
    return ret;
  }

  public bool LoadModel(byte[] data, int len, int index) {
    bool ret = EffekseerCorePINVOKE.EffekseerEffectCore_LoadModel(swigCPtr, data, len, index);
    return ret;
  }

  public bool HasModelLoaded(int index) {
    bool ret = EffekseerCorePINVOKE.EffekseerEffectCore_HasModelLoaded(swigCPtr, index);
    return ret;
  }

}

}
